# Generated by Django 5.0.3 on 2024-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
