# Generated by Django 5.0.4 on 2024-04-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_cart_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
    ]
