# Generated by Django 5.0.4 on 2024-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_remove_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hours_of_work',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='is_a_service',
            field=models.BooleanField(default=False),
        ),
    ]
