# Generated by Django 5.0.4 on 2024-04-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_hours_of_work_item_is_a_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hours_of_work',
        ),
    ]
